sudo: required
language: go
go:
  - 1.5.1
branches:
  only:
    - master
services:
  - docker
install:
  - make docker-build
script:
  - make test
deploy:
  provider: script
  script: _scripts/ci/deploy.sh
  on:
    branch: master
