sudo: required
language: go
go:
  - 1.5.1
branches:
  only:
    - master
services:
  - docker
install:
  - make build
script:
  - make test
deploy:
  provider: script
  script: contrib/ci/deploy.sh
  on:
    branch: master
