language: bash
branches:
  only:
    - master
sudo: required
services:
  - docker
env:
  # HACK(bacongobbler): make travis tests work
  - DEIS_REGISTRY=travis-ci/
install:
  - make docker-build
script:
  - make test
