apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/deis/postgres:2.0.0-alpha
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: "deis"
            - name: POSTGRES_PASSWORD
              value: "changeme123"
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - is_master
